### ISSUE TITLE
Could not build on macOS 12.0.1 and Apple M1 CPU.

### ISSUE THREAD

**Issue by satoy11** [iimachines/Maya2glTF#172]
I had a combination of macOS 12.0.1 and Apple M1 CPU fail in the build.
Is this test something I really need to do to build?

-- Configuring done
-- Generating done
-- Build files have been written to: /Users/satoy11/work/maya2gltf/Maya2glTF/build/GSL/src/GSL-build
[ 27%] Performing build step for 'GSL'
[ 17%] Built target catch
Consolidate compiler generated dependencies of target test_catch
[ 20%] Building CXX object tests/CMakeFiles/test_catch.dir/test.cpp.o
In file included from /Users/satoy11/work/maya2gltf/Maya2glTF/build/GSL/src/GSL/tests/test.cpp:26:
/Users/satoy11/work/maya2gltf/Maya2glTF/build/GSL/src/GSL-build/external/include/catch/catch.hpp:4167:13: error: unrecognized instruction mnemonic, did you mean: bit, cnt, hint, ins, not?
            CATCH_BREAK_INTO_DEBUGGER();
            ^
/Users/satoy11/work/maya2gltf/Maya2glTF/build/GSL/src/GSL-build/external/include/catch/catch.hpp:1392:75: note: expanded from macro 'CATCH_BREAK_INTO_DEBUGGER'
    #define CATCH_BREAK_INTO_DEBUGGER() if( Catch::isDebuggerActive() ) { CATCH_TRAP(); }
                                                                          ^
/Users/satoy11/work/maya2gltf/Maya2glTF/build/GSL/src/GSL-build/external/include/catch/catch.hpp:1371:34: note: expanded from macro 'CATCH_TRAP'
    #define CATCH_TRAP() __asm__("int $3\n" : : ) /* NOLINT */
                                 ^
<inline asm>:1:2: note: instantiated into assembly here
        int $3
        ^
1 error generated.
make[5]: *** [tests/CMakeFiles/test_catch.dir/test.cpp.o] Error 1
make[4]: *** [tests/CMakeFiles/test_catch.dir/all] Error 2
make[3]: *** [all] Error 2
make[2]: *** [GSL/src/GSL-stamp/GSL-build] Error 2
make[1]: *** [CMakeFiles/GSL.dir/all] Error 2
make: *** [all] Error 2

**Comment by Ziriax** [comment]
The plug-in is not supported on ARM CPUs unfortunately, but neither is Maya at the moment I think.

So on an ARM machine, you will need to target the x64 instruction set. 

I don’t know anything about a Mac, but you could try opening a terminal under Rosetta and then try building the plug-in?

https://www.bigbinary.com/learn-rubyonrails-book/setting-up-mac

**Comment by satoy11** [comment]
I enabled install-rosetta with the softwareupdate command and then set Terminal to use Rosetta.
However, the build result seems to be the same.

**Comment by Ziriax** [comment]
Unfortunately I don't have a MacBook Pro M1, so it is difficult to help you. You may always send me one of course, pun intended ;-)

So I can only Google around, guessing.

E.g. maybe this thread helps:

https://discourse.cmake.org/t/how-to-determine-which-architectures-are-available-apple-m1/2401
